site_name: 23L-TKOM

nav:
  - Projekt: index.md
  - Lekser: lexer.md
  - Parser: parser.md
  - Struktura programu: program_components.md
  - Interpreter: interpreter.md
  - Przykłady kodu: code_examples.md